[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip3 install --user -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python3 manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python3 manage.py migrate && python3 manage.py create_timeslots && gunicorn --bind 0.0.0.0:$PORT my_timetable.wsgi:application"
