[phases.setup]
nixPkgs = ["python39", "python39Packages.django", "python39Packages.pillow", "python39Packages.gunicorn", "python39Packages.psycopg2", "python39Packages.python-decouple", "python39Packages.whitenoise", "python39Packages.dj-database-url"]

[phases.install]
cmds = []

[phases.build]
cmds = ["cd backend && python3 manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python3 manage.py migrate && python3 manage.py create_timeslots && gunicorn --bind 0.0.0.0:$PORT my_timetable.wsgi:application"
