[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py create_timeslots && gunicorn --bind 0.0.0.0:$PORT my_timetable.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
